# mo-keeb's config file

[fonts]
[fonts.chars] # chars displayed when typed
name = "scientifica" # choices are ['scientifica', 'pixeldroid_menu', 'monocraft'], or any other system font
size = 48
color = "#f1faee" # as hex code
antialiasing = false # add antialiasing filter; false recommended for 'pixel art' fonts

[fonts.icons] # icons representing modifiers keys
name = "scientifica" # choices are ['scientifica', 'pixeldroid_menu', 'monocraft'], or any other system font
size = 24
color = "#caf0f8" # as hex code
antialiasing = false # add antialiasing filter; false recommended for 'pixel art' fonts

[paddings] # top, right, left, bottom
window = [10, 10, 10, 10]
icon = [5, 10, 5, 10]

[gaps]
below_chars = 10
between_icons = 5

[behavior]
max_age = 5 # in seconds
volume = 50 # from 0 to 100
backend = "auto" # choices are ['auto', 'pynput', 'keyboard']
profile = "brown" # choices are ['red', 'blue', 'brown']
