name: Python application

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "windows-latest"
          # - "ubuntu-latest"
          # - "macos-latest"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - run: pip install pipenv
    - run: pipenv install

    - name: Conditional deps for Windows
      run: pipenv install pywin32-ctypes
      if: runner.os == 'Windows'

    - run: pipenv run build
    # Optionally verify that it works (provided that it does not need user interaction)
    # - run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
