name: Python application

on:
  push:
    tags:
      - 'v*'

jobs:
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Output Release URL File
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - name: Save Release URL File for publish
        uses: actions/upload-artifact@v2
        with:
          name: release_url
          path: release_url.txt

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - run: pip install pipenv
      - run: pipenv install

      - name: Conditional deps for Windows
        run: pipenv install pywin32-ctypes
        if: runner.os == 'Windows'

      - name: Conditional deps for macOS
        run: pipenv install macholib
        if: runner.os == 'macOS'

      - run: pipenv run build
        env:
          OS_NAME: ${{ runner.os }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: dist/*

      - name: Load Release URL File from release job
        uses: actions/download-artifact@v1
        with:
          name: release_url
      - name: Get Release File Name & Upload URL
        id: get_release_info
        shell: bash
        run: |
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value
      - run: ls ./dist
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./dist/mo-keeb-${{ runner.os }}${{ ( runner.os == 'Windows' && '.exe' ) || ( runner.os == 'macOS' && '' ) || '' }}
          asset_name: mo-keeb_${{ runner.os }}${{ runner.os == 'Windows' && '.exe' || runner.os == 'macOS' && '.app' || '' }}
          asset_content_type: 'application/octet-stream'
